### ISSUE TITLE
player can remove 5th shard (which breaks the ending)

### ISSUE THREAD

**Issue by dit-zy** [Etherpod/Band-Together#1]
the door doesn't disable removal of the 5th shard, which causes problems if removed.

**Comment by JohnCorby** [comment]
more specifically it removes half of the "conditions" from the custom save file. i dont know why

**Comment by dit-zy** [comment]
fascinating. well, no more custom save file, so that is hopefully no longer a problem. but i still want to disable removing it so will do so

**Comment by dit-zy** [comment]
fixed. player can't remove the shard once inserted
