### ISSUE TITLE
Worship Ghirds don't move away from door

### ISSUE THREAD

**Issue by dit-zy** [Etherpod/Band-Together#14]

**Comment by JohnCorby** [comment]
they moved to the door for me, after placed the shrub on the table and went back into the room the lights were on and the ghosts werent there

maybe youre referring to something else though

**Comment by Etherpod** [comment]
I think it was they don't move away from the door

**Comment by dit-zy** [comment]
this might have been an issue with the npc away target. i redid all the targets for #6 so i think this works now
