### ISSUE TITLE
Dialogue is unable to handle multiple persistent conditions being set in the same node

### ISSUE THREAD

**Issue by dit-zy** [Etherpod/Band-Together#19]

**Comment by dit-zy** [comment]
we might be able to patch this, but worst case we can implement a condition listener that sets multiple persistent conditions based on the name of one non-persistent condition.

**Comment by JohnCorby** [comment]
this is base game behavior, the docs are just wrong. idk why base game does this, just wanted to let you know its not nh fault for once (except for the fact that the docs are wrong)

**Comment by dit-zy** [comment]
enhanced :D
