### ISSUE TITLE
persistent conditions for custom logic from code doesn't work

### ISSUE THREAD

**Issue by dit-zy** [Etherpod/Band-Together#3]
we created a custom persistent save mechanism because the existing mechanism didn't work for some reason. we should see if we can get the existing mechanism to work for us >:c

**Comment by JohnCorby** [comment]
etherpod skill issue

**Comment by JohnCorby** [comment]
also this is the cause of like half the bugs i encountered i think

**Comment by dit-zy** [comment]
fixed. will go into the next release.
