### ISSUE TITLE
call them inhabitants (base game explicitly calls them this) instead of ghirds

### ISSUE THREAD

**Issue by JohnCorby** [Etherpod/Band-Together#37]
most people do not know fanon/working names

**Comment by Etherpod** [comment]
And if someone doesn't know what Inhabitants are, they'll have to figure it out through context just like with Ghirds

**Comment by JohnCorby** [comment]
i think theyre at least referred to as inhabitants in base game so they have to go off of. thats why it should be used in the first place is cuz thats what dlc calls them

**Comment by dit-zy** [comment]
i don't understand why their name matters. the mod's story is having you encounter a new planet of people you don't know. relation to base game isn't relevant to the story. i should be able to meet a group of nomai looking people who say "hello, traveler. thank you for responding to our signal. our people are known as the flopoos".

**Comment by JohnCorby** [comment]
fair enough. that didnt seem clear to me that they were intentionally separate. given the nomai are still called nomai and the architecture and materials are the same as base game.

**Comment by dit-zy** [comment]
i wouldn't say they're "intentionally separate" as much as that i just think it's fine to introduce a new name, especially since the story is not connected to base game. ¯\\\_(ツ)_/¯
