### ISSUE TITLE
custom sound is way too loud for ditzy

### ISSUE THREAD

**Issue by dit-zy** [Etherpod/Band-Together#7]
all custom sounds are way too loud, but the ending is particularly deafening and doesn't respect audio source volume settings. etherpod does not have this problem, only ditzy so far.

**Comment by JohnCorby** [comment]
this also happened to me as well

as said in my duplicate issue, this is because the audio does not have mixer tracks assigned to them, whose settings are controlled by the settings. preferably these tracks would use the Music track

**Comment by dit-zy** [comment]
fixed! added an `OWAudioSource` to everything and set the tracks correctly.
