### ISSUE TITLE
NPCs all teleport to fire at once

### ISSUE THREAD

**Issue by dit-zy** [Etherpod/Band-Together#9]

**Comment by dit-zy** [comment]
they do? i thought we tested that the nomai and ghirds appear separately.

**Comment by Etherpod** [comment]
Oh maybe they do then, I'll check this off with the quantum NPCs then

**Comment by dit-zy** [comment]
i don't know what this was really complaining about, but with the rework on the npcs we know this behaves how we wanted it to, so let's close
